language: python

python:
  - 2.7
  - 3.5
  - 3.6

env:
  global:
    MACKEREL_APIKEY='xxxxxxxx'

before_install:
  - pip install -r requirements.txt
  - pip install coveralls

script: coverage run --source=mackerel.clienthde setup.py test

after_success: coveralls
